### ISSUE TITLE
Error on line 11

### ISSUE THREAD

**Issue by pixelbrackets** [plutov/o#5]
Fun script :)

I run into an error however when I try it on my local machine. 

Enviroment
* Ubuntu 16.04
* Github Repository

Error
> o.sh: 11: o.sh: Bad substitution

**Comment by plutov** [comment]
Thanks for feedback, I'm checking.

**Comment by plutov** [comment]
@pixelbrackets can you please try it one more time?

**Comment by pixelbrackets** [comment]
Works :)
